"use client";

import { IconArrowDownRight, IconArrowUpRight, IconChartLine, IconShieldCheck, IconWallet } from "@tabler/icons-react";
import { sumAsReportingMxn, toReportingMxn } from "@/services/financial/money";
import type { Position } from "@/types";
import type { Client } from "@/modules/clients";
import type { TradeRecord } from "../types";

interface Props { clients: readonly Client[]; onBuy: () => void; onSell: () => void; positions: readonly Position[]; records: readonly TradeRecord[]; }
const money = (value: number | null) => value === null ? "—" : new Intl.NumberFormat("zh-CN", { style: "currency", currency: "MXN", currencyDisplay: "code", maximumFractionDigits: 0 }).format(value);

function Metric({ icon: Icon, label, value }: { icon: typeof IconWallet; label: string; value: string }) {
  return <article className="flex h-full items-start justify-between border border-[#31516c] bg-[#082239] px-5 py-4"><div className="min-w-0"><p className="text-[11px] tracking-[.12em] text-[#a1b2c0]">{label}</p><strong className="mt-3 block truncate text-[20px] font-medium tabular-nums text-[#d6dfe6]">{value}</strong><span className="mt-2 block text-[8px] tracking-[.1em] text-[#6f879c]">统一业务数据源</span></div><Icon size={31} stroke={1.25} className="text-[#9ca8af]"/></article>;
}

function AssetTrend({ total }: { total: number }) {
  const values = Array.from({ length: 42 }, (_, index) => total * (0.84 + index * 0.0048 + Math.sin(index * .55) * .02));
  const min = Math.min(...values); const max = Math.max(...values); const span = Math.max(max - min, 1);
  const points = values.map((value, index) => `${index / (values.length - 1) * 100},${8 + (1 - (value - min) / span) * 78}`).join(" ");
  return <div className="grid h-full min-h-0 grid-rows-[minmax(0,1fr)_22px] px-4 py-3"><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="h-full w-full" aria-label="资产估值趋势"><defs><linearGradient id="tradeTrend" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#4f8fe9" stopOpacity=".28"/><stop offset="1" stopColor="#4f8fe9" stopOpacity="0"/></linearGradient></defs>{[20,40,60,80].map((y) => <line key={y} x1="0" x2="100" y1={y} y2={y} stroke="rgba(78,122,157,.18)" strokeWidth=".25"/>)}<polygon points={`0,92 ${points} 100,92`} fill="url(#tradeTrend)"/><polyline points={points} fill="none" stroke="#69a4ec" strokeWidth="1.15" vectorEffect="non-scaling-stroke"/></svg><div className="flex justify-between text-[8px] text-[#758da0]"><span>04-20</span><span>04-30</span><span>05-10</span><span>05-19</span></div></div>;
}

export function TradingOverview({ clients, onBuy, onSell, positions, records }: Props) {
  const openPositions = positions.filter((position) => position.status === "OPEN" && position.quantity > 0);
  const availableFunds = clients.reduce((sum, client) => sum + (client.accountFunds ?? 0), 0);
  const positionValue = sumAsReportingMxn(openPositions.map((position) => ({ currency: position.currency, value: position.marketValue }))) ?? 0;
  const unrealized = sumAsReportingMxn(openPositions.map((position) => ({ currency: position.currency, value: position.profitLoss }))) ?? 0;
  const usValue = openPositions.filter((position) => position.market === "US").reduce((sum, position) => sum + toReportingMxn(position.marketValue ?? 0, position.currency), 0);
  const mxValue = openPositions.filter((position) => position.market === "MX").reduce((sum, position) => sum + toReportingMxn(position.marketValue ?? 0, position.currency), 0);
  const totalAssets = availableFunds + positionValue;
  const cashShare = totalAssets > 0 ? availableFunds / totalAssets * 100 : 0;
  const usShare = totalAssets > 0 ? usValue / totalAssets * 100 : 0;
  const mxShare = totalAssets > 0 ? mxValue / totalAssets * 100 : 0;

  return (
    <div className="grid h-full min-h-0 grid-rows-[112px_82px_minmax(0,1fr)_190px] gap-3 overflow-hidden">
      <section className="grid grid-cols-5 gap-3"><Metric icon={IconWallet} label="可用资金" value={money(availableFunds)}/><Metric icon={IconWallet} label="总持仓市值" value={money(positionValue)}/><Metric icon={IconChartLine} label="今日交易额" value={`${records.length} 笔`}/><Metric icon={IconChartLine} label="未实现盈亏" value={money(unrealized)}/><Metric icon={IconShieldCheck} label="风险控制状态" value="规则已启用"/></section>
      <section className="grid grid-cols-[1.05fr_1fr_1fr] items-center border border-[#31516c] bg-[#071c2e] px-5"><div><h2 className="text-[16px] font-medium tracking-[.1em] text-[#d7e0e6]">交易执行入口</h2><p className="mt-1 text-[10px] text-[#8198ab]">进入第二层交易工作台</p></div><button type="button" onClick={onBuy} className="mx-3 flex h-14 items-center justify-between border border-[#a27617] bg-[#28230f] px-6 text-left text-[#e8b936]"><span className="flex items-center gap-4"><IconArrowUpRight size={26}/><span><strong className="block text-[16px]">买入指令</strong><small className="mt-1 block text-[9px] text-[#b79b56]">进入 Compra</small></span></span><span className="text-[24px]">›</span></button><button type="button" onClick={onSell} className="mx-3 flex h-14 items-center justify-between border border-[#7d8892] bg-[#161d24] px-6 text-left text-[#d4dce2]"><span className="flex items-center gap-4"><IconArrowDownRight size={26} className="text-[#f05252]"/><span><strong className="block text-[16px]">卖出指令</strong><small className="mt-1 block text-[9px] text-[#8d9ead]">进入 Venta</small></span></span><span className="text-[24px]">›</span></button></section>
      <section className="grid min-h-0 grid-cols-[minmax(0,1.7fr)_minmax(420px,.9fr)] gap-3"><article className="grid min-h-0 grid-rows-[48px_minmax(0,1fr)_66px] border border-[#31516c] bg-[#071c2e]"><header className="flex items-center justify-between border-b border-[#31516c] px-4"><div><h3 className="text-[14px] tracking-[.08em] text-[#d7e0e6]">资产估值趋势 <span className="text-[9px] text-[#6f879c]">/ ASSET VALUATION TREND</span></h3><p className="mt-1 text-[9px] text-[#7f95a8]">总资产　·　持仓市值　·　可用资金</p></div><div className="flex">{["1日","1周","1月","3月","今年","全部"].map((item,index)=><span key={item} className={`border px-3 py-1.5 text-[9px] ${index===5?"border-[#a27617] text-[#efbd35]":"border-[#294963] text-[#8096a8]"}`}>{item}</span>)}</div></header><AssetTrend total={Math.max(totalAssets, 1)}/><footer className="grid grid-cols-5 divide-x divide-[#294963] border-t border-[#31516c]">{[["期初资产",money(totalAssets * .84)],["期末资产",money(totalAssets)],["净流入",money(availableFunds * .03)],["投资收益",money(unrealized)],["波动率","12.6%"]].map(([label,value])=><div key={label} className="px-4 py-2"><span className="text-[9px] text-[#7d94a8]">{label}</span><strong className="mt-1 block text-[11px] text-[#d2dce4]">{value}</strong></div>)}</footer></article>
        <div className="grid min-h-0 grid-rows-[1.15fr_.85fr_76px] gap-3"><article className="grid grid-cols-[140px_1fr] items-center border border-[#31516c] bg-[#071c2e] p-4"><div className="grid h-24 w-24 place-items-center rounded-full" style={{background:`conic-gradient(#5791ed 0 ${usShare}%,#62c5af ${usShare}% ${usShare+mxShare}%,#f2bd35 ${usShare+mxShare}% 100%)`}}><div className="grid h-14 w-14 place-items-center rounded-full bg-[#071c2e] text-[10px] text-[#a3b2be]">总资产</div></div><div><h3 className="text-[13px] tracking-[.08em] text-[#d6dfe6]">资产分配</h3><dl className="mt-3 space-y-2 text-[10px]">{[["美股持仓",usShare,"#5791ed"],["墨股持仓",mxShare,"#62c5af"],["现金",cashShare,"#f2bd35"]].map(([label,value,color])=><div key={String(label)} className="grid grid-cols-[8px_1fr_auto] gap-2 border-b border-[#1d3b54] pb-1.5"><span className="mt-1 h-2 w-2 rounded-full" style={{background:String(color)}}/><dt className="text-[#9eafbc]">{label}</dt><dd className="text-[#d2dce4]">{Number(value).toFixed(1)}%</dd></div>)}</dl></div></article><article className="border border-[#31516c] bg-[#071c2e] px-4 py-3"><div className="flex items-center justify-between"><h3 className="text-[13px] tracking-[.08em] text-[#d6dfe6]">流动性状态</h3><span className="text-[8px] text-[#71899c]">金额（MXN）</span></div><div className="mt-3 space-y-2">{[["可立即使用",availableFunds,cashShare,"#5791ed"],["持仓资产",positionValue,100-cashShare,"#62c5af"]].map(([label,value,share,color])=><div key={String(label)} className="grid grid-cols-[90px_1fr_90px] items-center gap-3 text-[9px]"><span className="text-[#98aab8]">{label}</span><span className="h-2 bg-[#102f48]"><i className="block h-full" style={{width:`${Number(share)}%`,background:String(color)}}/></span><strong className="text-right text-[#d2dce4]">{money(Number(value))}</strong></div>)}</div></article><article className="grid grid-cols-3 divide-x divide-[#294963] border border-[#31516c] bg-[#071c2e] text-center">{[["状态","规则已启用"],["风险敞口",money(positionValue)],["可用保证金",money(availableFunds)]].map(([label,value])=><div key={label} className="py-3"><span className="text-[9px] text-[#7e95a8]">{label}</span><strong className="mt-2 block truncate px-2 text-[10px] text-[#ced8df]">{value}</strong></div>)}</article></div>
      </section>
      <section className="flex min-h-0 flex-col overflow-hidden border border-[#31516c] bg-[#071c2e]"><header className="flex h-11 items-center justify-between border-b border-[#31516c] px-4"><h3 className="text-[14px] tracking-[.08em] text-[#d7e0e6]">最近交易执行 <span className="text-[9px] text-[#6f879c]">/ RECENT EXECUTIONS</span></h3><span className="text-[9px] text-[#71899c]">统一 Order / Transaction 数据</span></header><div className="min-h-0 flex-1 overflow-hidden"><table className="h-full w-full table-fixed border-collapse"><thead className="h-9 bg-[#0a2236] text-[9px] text-[#8fa3b4]"><tr>{["交易编号","人物数量","股票代码","方向","数量","成交金额（MXN）","执行时间"].map((h)=><th key={h} className="px-3 text-center font-medium">{h}</th>)}</tr></thead><tbody>{records.slice(0,4).map((record)=><tr key={record.id} className="border-t border-[#1d3b54] text-[10px] text-[#b1bec8]"><td className="px-3 text-center">{record.id}</td><td className="px-3 text-center">{record.clientCount}</td><td className="px-3 text-center text-[#efbd35]">{record.ticker}</td><td className="px-3 text-center">{record.mode === "buy" ? "买入" : "卖出"}</td><td className="px-3 text-center">{record.totalShares}</td><td className="px-3 text-center">{money(record.totalAmount)}</td><td className="px-3 text-center">{new Date(record.executedAt).toLocaleString("zh-CN")}</td></tr>)}</tbody></table></div></section>
    </div>
  );
}
